version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = ["GoEchoFunction=229531317943.dkr.ecr.ap-south-1.amazonaws.com/samapp7427b055/goechofunction06fa5ec4repo"]
